
- name: openrouter/deepseek/deepseek-r1
  extra_params:
      extra_body:
          provider:
              order: ["SambaNova", "Fireworks", "Together"]
              # Don't fall back to other providers
              allow_fallbacks: false
              # Skip providers that may train on inputs
              data_collection: "deny"
              # Only use providers supporting all parameters
              require_parameters: true

- name: openrouter/deepseek/deepseek-chat
  extra_params:
      extra_body:
          provider:
              order: ["Fireworks", "Together"]

