import = [
  "~/.config/alacritty/carbonfox.toml"
]

[window]
decorations = "Transparent"
decorations_theme_variant = "Dark"
startup_mode = "Maximized"
opacity = 0.9
dynamic_padding = true

[font]
normal = { family = "Cascadia Code NF" }
size = 15

[cursor]
style = { shape = "Block", blinking = "Always" }
