[language-server.phpactor]
command = "phpactor"
args = ["language-server"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "php"
scope = "source.php"
injection-regex = "php"
file-types = ["php", "inc", "php4", "php5", "phtml", "ctp", "blade"]
shebangs = ["php"]
roots = ["composer.json", "index.php"]
language-servers = ["phpactor", "intelephense", "tailwindcss-ls", "emmet-lsp"]
formatter = { command = "pint", args = ["--stdin-filename=%{buffer_name}"]}

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls", "emmet-lsp"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "blade"
scope = "source.blade.php"
file-types = [{ glob = "*.blade.php" }, "blade"]
injection-regex = "blade"
roots = ["composer.json", "index.php"]
language-servers = ["tailwindcss-ls", "emmet-lsp"]
